-- Active: 1773421575078@@127.0.0.1@3306
CREATE TABLE dono (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cpf INTEGER NOT NULL UNIQUE,
    numero INTEGER NOT NULL UNIQUE,
    idade INTEGER NOT NULL
)